// Package assets exposes the embedded harness mirrors, scaffold templates, and
// splash art that are bundled into the ui-craft binary at build time.
//
// CI ordering dependency (gotcha #5):
//
//	The `sync-harnesses.mjs` script MUST run and copy its output into
//	cli/assets/mirrors/<harness>/ BEFORE `go build` executes.  The init()
//	guard below will panic if the mirrors subtree is empty, catching any CI
//	step-ordering bug at build verification time rather than at install time.
//
// TODO(gotcha#5): Once CI wiring lands (Slice 5), the mirrorsFSNonEmpty()
// assertion in init() will fire against real mirror content.  Until then the
// placeholder VERSION file keeps the embed valid and the guard dormant.
//
// Review agent definitions (Slice 8):
//
//	Agent definitions are committed directly under cli/assets/agents/<harness>/
//	(not generated by CI) because they originate from the canonical agents/
//	directory at the repo root. They are NOT automatically kept in sync — drift
//	between agents/ and cli/assets/agents/claude/ is caught by:
//	  make check-agent-copies   (developer gate)
//	  CI workflow on agents/** and cli/** changes (automated gate)
//	Two harness-specific subdirectories are embedded:
//	  agents/claude/  — Claude Code sub-agent format (name, description, tools, model, color)
//	  agents/opencode/ — OpenCode agent format (name, description only)
package assets

import (
	"embed"
	"fmt"
	"io/fs"
	"strings"
)

//go:embed mirrors
var mirrorsFS embed.FS

//go:embed templates
var templatesFS embed.FS

//go:embed art
var artFS embed.FS

// agentsEmbedFS holds the review agent definition files. Unlike mirrors/, this
// directory is committed (not CI-generated) because agent definitions originate
// from the canonical agents/ directory at the repo root. Drift between
// agents/ and cli/assets/agents/claude/ is enforced by `make check-agent-copies`
// and the CI workflow. Two harness-specific subdirectories are included:
//
//   - agents/claude/  — Claude Code sub-agent format
//   - agents/opencode/ — OpenCode agent format
//
//go:embed agents
var agentsEmbedFS embed.FS

// MirrorFS returns the embedded FS rooted at "mirrors/".
func MirrorFS() fs.FS {
	sub, err := fs.Sub(mirrorsFS, "mirrors")
	if err != nil {
		panic("assets: cannot sub mirrorsFS: " + err.Error())
	}
	return sub
}

// TemplateFS returns the embedded FS rooted at "templates/".
func TemplateFS() fs.FS {
	sub, err := fs.Sub(templatesFS, "templates")
	if err != nil {
		panic("assets: cannot sub templatesFS: " + err.Error())
	}
	return sub
}

// ArtFS returns the embedded FS rooted at "art/".
func ArtFS() fs.FS {
	sub, err := fs.Sub(artFS, "art")
	if err != nil {
		panic("assets: cannot sub artFS: " + err.Error())
	}
	return sub
}

// MirrorVersion returns the version stamp embedded in mirrors/VERSION.
// Returns "unknown" if the file is absent or unreadable.
func MirrorVersion() string {
	data, err := mirrorsFS.ReadFile("mirrors/VERSION")
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(data))
}

// Mirror returns the embedded sub-filesystem for the named harness
// (e.g. "claude", "cursor", "codex", "gemini", "opencode"). The returned
// fs.FS is rooted at mirrors/<harness>/ so callers can walk it directly.
// Returns nil when the harness subtree does not exist in the embedded mirrors
// (e.g. CI sync step did not run — see gotcha #5).
func Mirror(harnessName string) fs.FS {
	path := "mirrors/" + harnessName
	// Validate that the subtree directory actually exists in the embed before
	// returning a sub-FS. fs.Sub itself succeeds even for absent dirs on embed.FS.
	if _, err := fs.Stat(mirrorsFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(mirrorsFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// Agents returns the embedded sub-filesystem containing the review agent
// definitions for the named harness (e.g. "claude", "opencode"). The returned
// fs.FS is rooted at agents/<harness>/ so callers can walk it directly and write
// each .md file as a separate agent.
//
// Agent definitions are committed in cli/assets/agents/<harness>/ (not
// CI-generated) because they originate from the canonical agents/ directory at
// the repository root. They are always available in dev and CI builds — no sync
// step is required.
//
// Returns nil when:
//   - The harness does not support native sub-agents (Cursor, Codex, Gemini have
//     no subdirectory under agents/ and are therefore absent from agentsEmbedFS).
//   - The harness subtree is absent for any other reason (defensive guard).
//
// Callers (core.Plan AgentProvider) must treat nil as "skip gracefully".
func Agents(harnessName string) fs.FS {
	path := "agents/" + harnessName
	if _, err := fs.Stat(agentsEmbedFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(agentsEmbedFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// mirrorsFSNonEmpty returns true when at least one non-.gitkeep file exists
// under the mirrors/ subtree. Used by the init() guard below.
func mirrorsFSNonEmpty() bool {
	found := false
	_ = fs.WalkDir(mirrorsFS, "mirrors", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		// .gitkeep and VERSION are scaffold-only; real content = anything else.
		base := d.Name()
		if base == ".gitkeep" {
			return nil
		}
		if path == "mirrors/VERSION" {
			return nil
		}
		found = true
		return fs.SkipAll
	})
	return found
}

// expectedHarnesses lists the harness subtrees that must be present in the
// mirrors/ embed once CI has run sync-harnesses.mjs (gotcha #5).
var expectedHarnesses = []string{"claude", "cursor", "codex", "gemini", "opencode"}

// mirrorHarnessPresent returns true when at least one non-.gitkeep file exists
// under mirrors/<harness>/.
func mirrorHarnessPresent(harnessName string) bool {
	found := false
	root := "mirrors/" + harnessName
	_ = fs.WalkDir(mirrorsFS, root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if d.Name() != ".gitkeep" {
			found = true
			return fs.SkipAll
		}
		return nil
	})
	return found
}

// AssertMirrorsFresh returns an error if any expected harness subtree is missing
// real content. This is called at install/update time (not in init()) so
// development builds and tests using fixture mirrors are unaffected. CI ensures
// sync-harnesses.mjs runs before go build, making real mirrors available
// (gotcha #5).
//
// Call this as the FIRST statement in any cmd RunE that performs WriteSkill ops.
func AssertMirrorsFresh() error {
	for _, h := range expectedHarnesses {
		if !mirrorHarnessPresent(h) {
			return fmt.Errorf("assets: mirrors/%s/ is empty or placeholder — run `make gen-mirrors` before building (gotcha #5)", h)
		}
	}
	return nil
}

// assertMirrorsFreshSeam is the init()-time seam. During development (Slices
// 1–5) mirrors/ may contain only placeholders, so we skip the panic to allow
// `go build ./...` and `go test ./...` to pass without a CI sync step.
// The real freshness check is performed at install time via AssertMirrorsFresh.
func assertMirrorsFreshSeam() {
	// No-op at init time: AssertMirrorsFresh() is called at install time instead.
	// This preserves go build / go test ergonomics on developer machines.
}

func init() {
	assertMirrorsFreshSeam()
}
