// Package assets exposes the embedded harness mirrors, scaffold templates, and
// splash art that are bundled into the ui-craft binary at build time.
//
// Harness mirrors are committed directly under cli/assets/mirrors/<harness>/
// (gentle-ai model — no generate step, no runtime freshness guard). If mirrors
// are missing, //go:embed fails at BUILD time with a clear error — that is the
// intended signal. To regenerate mirrors from source, run `make gen-mirrors`
// and commit the result.
//
// Mirror drift (skills/ edited without regenerating mirrors) is caught at PR
// time by the `make check-mirrors` / CI check-mirrors step.
//
// Review agent definitions (Slice 8):
//
//	Agent definitions are committed directly under cli/assets/agents/<harness>/
//	(not generated by CI) because they originate from the canonical agents/
//	directory at the repo root. They are NOT automatically kept in sync — drift
//	between agents/ and cli/assets/agents/claude/ is caught by:
//	  make check-agent-copies   (developer gate)
//	  CI workflow on agents/** and cli/** changes (automated gate)
//	Two harness-specific subdirectories are embedded:
//	  agents/claude/  — Claude Code sub-agent format (name, description, tools, model, color)
//	  agents/opencode/ — OpenCode agent format (name, description only)
package assets

import (
	"embed"
	"io/fs"
	"strings"
)

//go:embed mirrors
var mirrorsFS embed.FS

//go:embed templates
var templatesFS embed.FS

//go:embed art
var artFS embed.FS

// agentsEmbedFS holds the review agent definition files. Unlike mirrors/, this
// directory is committed (not CI-generated) because agent definitions originate
// from the canonical agents/ directory at the repo root. Drift between
// agents/ and cli/assets/agents/claude/ is enforced by `make check-agent-copies`
// and the CI workflow. Two harness-specific subdirectories are included:
//
//   - agents/claude/  — Claude Code sub-agent format
//   - agents/opencode/ — OpenCode agent format
//
//go:embed agents
var agentsEmbedFS embed.FS

// MirrorFS returns the embedded FS rooted at "mirrors/".
func MirrorFS() fs.FS {
	sub, err := fs.Sub(mirrorsFS, "mirrors")
	if err != nil {
		panic("assets: cannot sub mirrorsFS: " + err.Error())
	}
	return sub
}

// TemplateFS returns the embedded FS rooted at "templates/".
func TemplateFS() fs.FS {
	sub, err := fs.Sub(templatesFS, "templates")
	if err != nil {
		panic("assets: cannot sub templatesFS: " + err.Error())
	}
	return sub
}

// ArtFS returns the embedded FS rooted at "art/".
func ArtFS() fs.FS {
	sub, err := fs.Sub(artFS, "art")
	if err != nil {
		panic("assets: cannot sub artFS: " + err.Error())
	}
	return sub
}

// MirrorVersion returns the version stamp embedded in mirrors/VERSION.
// Returns "unknown" if the file is absent or unreadable.
func MirrorVersion() string {
	data, err := mirrorsFS.ReadFile("mirrors/VERSION")
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(data))
}

// Mirror returns the embedded sub-filesystem for the named harness
// (e.g. "claude", "cursor", "codex", "gemini", "opencode"). The returned
// fs.FS is rooted at mirrors/<harness>/ so callers can walk it directly.
// Returns nil when the harness subtree does not exist in the embedded mirrors.
func Mirror(harnessName string) fs.FS {
	path := "mirrors/" + harnessName
	// Validate that the subtree directory actually exists in the embed before
	// returning a sub-FS. fs.Sub itself succeeds even for absent dirs on embed.FS.
	if _, err := fs.Stat(mirrorsFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(mirrorsFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// Agents returns the embedded sub-filesystem containing the review agent
// definitions for the named harness (e.g. "claude", "opencode"). The returned
// fs.FS is rooted at agents/<harness>/ so callers can walk it directly and write
// each .md file as a separate agent.
//
// Agent definitions are committed in cli/assets/agents/<harness>/ (not
// CI-generated) because they originate from the canonical agents/ directory at
// the repository root. They are always available in dev and CI builds — no sync
// step is required.
//
// Returns nil when:
//   - The harness does not support native sub-agents (Cursor, Codex, Gemini have
//     no subdirectory under agents/ and are therefore absent from agentsEmbedFS).
//   - The harness subtree is absent for any other reason (defensive guard).
//
// Callers (core.Plan AgentProvider) must treat nil as "skip gracefully".
func Agents(harnessName string) fs.FS {
	path := "agents/" + harnessName
	if _, err := fs.Stat(agentsEmbedFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(agentsEmbedFS, path)
	if err != nil {
		return nil
	}
	return sub
}
